-- Lesson Plan Generator Database Schema
-- Run this in Supabase SQL Editor

-- 1. Metadata for Books
CREATE TABLE IF NOT EXISTS textbooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    grade_level VARCHAR(10),      -- e.g., "Grade 2"
    subject VARCHAR(50),          -- e.g., "Mathematics" / "English"
    book_type VARCHAR(50),        -- "course_book" / "workbook" / "learners" / "activity" / "reading"
    title VARCHAR(100)
);

-- 2. Stores OCR Content per Page
CREATE TABLE IF NOT EXISTS textbook_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES textbooks(id) ON DELETE CASCADE,
    page_number INT,
    content_text TEXT,            -- Raw OCR text
    image_summary TEXT,           -- AI description of diagrams/images on page
    has_exercises BOOLEAN DEFAULT FALSE,
    exercise_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(book_id, page_number)
);

-- 3. Stores Parsed SOW Strategies
CREATE TABLE IF NOT EXISTS sow_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    grade_level VARCHAR(10),
    subject VARCHAR(50),
    term VARCHAR(20),
    
    -- The Core Linkage Data
    topic_name VARCHAR(200),           -- e.g., "Clockwise Movement"
    mapped_page_numbers INT[],         -- Array of ints: [144, 145, 146]
    
    -- The Pedagogical Content
    teaching_strategy TEXT,            -- From "Teaching Strategies" column
    resources_text TEXT,               -- From "Digital Resources" column
    afl_strategy TEXT,                 -- From "Assessment" column
    activities TEXT                    -- Extracted specific activities
);

-- Indexing for Faster Retrieval
CREATE INDEX IF NOT EXISTS idx_textbook_pages_lookup ON textbook_pages(book_id, page_number);
CREATE INDEX IF NOT EXISTS idx_textbooks_subject ON textbooks(subject, grade_level, book_type);
CREATE INDEX IF NOT EXISTS idx_sow_topic ON sow_entries(topic_name);
CREATE INDEX IF NOT EXISTS idx_sow_subject ON sow_entries(subject, grade_level);
CREATE INDEX IF NOT EXISTS idx_sow_pages ON sow_entries USING GIN(mapped_page_numbers);
