-- Lesson Plan Generator Database Schema
-- Run this in Supabase SQL Editor

-- 1. Metadata for Books
CREATE TABLE IF NOT EXISTS textbooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    grade_level VARCHAR(10),      -- e.g., "Grade 2"
    subject VARCHAR(50),          -- e.g., "Mathematics" / "English"
    book_type VARCHAR(50),        -- "course_book" / "workbook" / "learners" / "activity" / "reading"
    title VARCHAR(100),
    -- OCR content stored as JSONB array: [{"book_text": "...", "page_no": 1}, ...]
    -- Images in text are formatted as: [object: description...]
    pages JSONB DEFAULT '[]'::jsonb
);

-- 2. Stores Complete SOW Extraction as JSON
CREATE TABLE IF NOT EXISTS sow_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    grade_level VARCHAR(10),
    subject VARCHAR(50),
    term VARCHAR(20),
    title VARCHAR(200),           -- Document title/filename
    
    -- Complete extraction stored as JSONB
    -- Contains the full structured output from ADE extract
    extraction JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Indexing for Faster Retrieval
CREATE INDEX IF NOT EXISTS idx_textbooks_subject ON textbooks(subject, grade_level, book_type);
CREATE INDEX IF NOT EXISTS idx_sow_subject ON sow_entries(subject, grade_level);
CREATE INDEX IF NOT EXISTS idx_sow_extraction ON sow_entries USING GIN(extraction);

-- 3. Stores Generated Lesson Plans
CREATE TABLE IF NOT EXISTS lesson_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Request Parameters
    grade_level VARCHAR(10),
    subject VARCHAR(50),
    lesson_type VARCHAR(50),
    page_start INT,
    page_end INT,
    topic VARCHAR(200),
    
    -- Generated Content (stored as JSON)
    lesson_plan JSONB NOT NULL,
    
    -- Metadata
    textbook_id BIGINT REFERENCES textbooks(id),
    sow_entry_id BIGINT REFERENCES sow_entries(id)
);

CREATE INDEX IF NOT EXISTS idx_lesson_plans_lookup ON lesson_plans(subject, grade_level, lesson_type);
