-- Lesson Plan Generator Database Schema
-- Run this in Supabase SQL Editor

-- 1. Metadata for Books
create table public.textbooks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  grade_level character varying(10) null,
  subject character varying(50) null,
  book_type character varying(50) null,
  title character varying(100) null,
  content_text jsonb null,
  book_tag text null,
  constraint textbooks_pkey primary key (id)
) TABLESPACE pg_default;

-- 2. Stores Complete SOW Extraction as JSON
CREATE TABLE IF NOT EXISTS sow_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    grade_level VARCHAR(10),
    subject VARCHAR(50),
    term VARCHAR(20),
    title VARCHAR(200),           -- Document title/filename

    -- Complete extraction stored as JSONB
    -- Contains the full structured output from ADE extract
    extraction JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Indexing for Faster Retrieval
create index IF not exists idx_textbooks_subject on public.textbooks using btree (subject, grade_level, book_type) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_sow_subject ON sow_entries(subject, grade_level);
CREATE INDEX IF NOT EXISTS idx_sow_extraction ON sow_entries USING GIN(extraction);

-- 3. Stores Generated Lesson Plans
CREATE TABLE IF NOT EXISTS lesson_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Request Parameters
    grade_level VARCHAR(10),
    subject VARCHAR(50),
    lesson_type VARCHAR(50),
    page_start INT,
    page_end INT,
    topic VARCHAR(200),

    -- Generated Content (stored as JSON)
    lesson_plan JSONB NOT NULL,

    -- Metadata
    textbook_id BIGINT REFERENCES textbooks(id),
    sow_entry_id BIGINT REFERENCES sow_entries(id),

    -- Usage Metrics and Other Metadata (stored as JSON)
    -- Example: {"generation_time": 3.45, "cost": 0.002341, "input_tokens": 1234, "output_tokens": 567, "total_tokens": 1801}
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_lesson_plans_lookup ON lesson_plans(subject, grade_level, lesson_type);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_metadata ON lesson_plans USING GIN(metadata);

-- 4. User Profiles (Linked to Auth)
CREATE TABLE IF NOT EXISTS public.users (
  id uuid REFERENCES auth.users on delete cascade not null primary key,
  created_at timestamp with time zone null default now(),
  first_name text,
  last_name text,
  grade text,
  subject text,
  school_branch text,
  email text,
  role text,
  is_approved boolean default true
);
